### ISSUE TITLE
原文のファイルフォーマットについて

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#11]
fyi @ystk 
Slack に載せられた内容を代理してIssue としてあげます。

**原文のファイルのフォーマットについて**

- Learning parh だと、（微妙な所はありますが）一行一文と決まっていて、ある意味作業はしやすかった 
- InnerSource Commons の何に合わせるかだとは思う
- テキストファイルを読むとなるとまた別の観点になるとは思う

**Comment by ystk** [comment]
個人的には、英語の一文を一行にするというルールが嬉しいです。
あえて「英語の」としたのは、日本語で翻訳するときに文を分けることもあると思い、そう書いています。
以下のようなポイントが理由でしょうか。

- 行数で翻訳忘れをチェックできる
- textlintの指摘箇所をチェックしやすい
- 一文を複数に分ける頻度は多くなさそう
- テキストで直接読む人は、多くないかもしれない。

先ほどtextlintでチェックした際、指摘されたポイントが一行の中のどの文を指すのかわからず、一文を一行に変換してから修正し、再結合という作業になって、そう思った次第です。

**Comment by masskaneko** [comment]
[8/9 の会議](https://innersourcecommons.notion.site/2022-08-09-Agenda-Getting-Started-with-InnerSource-791cc72937324f9a90928fb8d92e8a58) でやることに決まりました。
ほかに Pull Request も出ていない今、私がささっとやることにします。

**Comment by masskaneko** [comment]
#24 でインナーソース入門(Getting Started with InnerSource)の訳文を1文1行の形式にしました。
訳文のポリシーにも記載しておくことに気づいて #25 を作りました。
#25 がマージされたらこの Issue をクローズしようと思います。

**Comment by yuhattor** [comment]
Close します！
