### ISSUE TITLE
textlint check on GitHub Actions

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#13]
2022/07/26 の第一回 Meeting で決まった初期ルールがありますが、パイプラインとして実装したいと思います。
https://innersourcecommons.notion.site/2022-07-25-Agenda-5d2a1bdebeb842b197af8b16edadc91c

- [x] GitHub Actions 用にルールを簡素化 (Initial のゆるいルール)
- [x] Pipeline の実装

**Comment by bory-kb** [comment]
Textlint のゆるいルールに関しては要議論だと思いますが着手します

**Comment by yuhattor** [comment]
はいー、ぜひコミュニケーション取りながらやりましょう！

**Comment by bory-kb** [comment]
2022/07/26 の第一回 Meeting で決まった初期ルールのうち簡単に設定できる以下を今回の Issue の PullRequest に含めようと思います。
これらは textlint の rules.yml ファイルに拒否するワードとそれに対応する許可するワードを併記するだけで設定ができ、文脈にかかわらず一貫してルールとして適用できるためです。

・コントリビューション / 貢献 → コントリビューション
・リポジトリ / レポジトリ → リポジトリ
・単体テスト / ユニットテスト → ユニットテスト
・InnerSource / インナーソース → インナーソース
・ドキュメント/文書 → ドキュメント
・かっこは全角ではなく半角

**Comment by bory-kb** [comment]
Translation Policy にこの Issue で対応するルールを記載する予定です。

**Comment by bory-kb** [comment]
GitHub Actions の動作を見るためにゴミコミットを量産したので、Pull request は Squash Merge で対応しようと考えていますが、このリポジトリでは許可されていますか？

**Comment by yuhattor** [comment]
ありがとうございます！ベースとしては良いのではないでしょうか。よろしくお願いします。

単語の対応だけに限って言えば、Translation Policy にはルールファイルのパスを指し示すだけでも良いかもしれません。ポリシードキュメントと定義ファイルの二重管理は面倒かなと思います。
ここは、皆さんの意見を聞きたいところですね

- [ ] textllint の定義ファイルと policy(読み物) の管理について管理方法を決定

> Pull request は Squash Merge で対応しようと考えていますが、このリポジトリでは許可されていますか？

そうですね。特に今のところNGとかはないですが、ひとまず @bory-kb さんの手元で squash していただいた方がシンプルかもしれません。
ただ、InnerSource Patterns のリポジトリでもメンバーが “1st check”、とか “2nd try” とか(すみません、これは私も含めてです) のメッセージを含めたコミットをそのまま入れてしまっているケースもあるので、InnerSource Commons 全体としても必ずしも厳格にルールが決まっているわけではないのかなと思います。程度問題かなと、、

あんまりキツくルールをしてもPR しにくくなると思いますが、最低限の整理は必要だと思いますので、次回以降方針について話し合ってみましょうか

**Comment by bory-kb** [comment]
Translation Policy について
textllint の定義ファイルは用語の統一の設定を記載する rules.yml と文体の統一など文章の校正の設定を記載する .textlintrc ファイルの二つにわかれています。ですのでルールファイルのパスを記載するのみとすると、これら二つのファイルを参照することになると思います。
ルールを確認するとき参照先が二つのファイルになるので多少面倒かもしれませんが。ポリシードキュメントとこの定義ファイルの二重管理のほうがより手間かもしれないですね…

Squash Merge について
たしかに手元で Squash するという発想がなかったです、やってみます。
今回は GitHub Actions 実行のためにコミットを量産してしまったので、本来の翻訳プロジェクトとして発生するコミット量であれば許容範囲じゃないかなと思っています。（あくまで想像ですが…）

**Comment by masskaneko** [comment]
着手ありがとうございます。textlint を提案した私も GitHub Actions でできればよいと考えはしましたが、使い方がわかってなかったのでローカルでの手順のみ書きました。

lint については複数の議題が出ていますが、この Issue は "textlint check on GitHub Actions" ですので、まずは textlint を GitHub Actions で動かせるようにしませんか。おそらく結果をどう出すか、バッジに出すか、Pull Request のクローズ条件に応用するかといった工夫もあると思いますが、まずは単純にコマンドラインの出力結果が出るだけでよいと思います。

**Comment by bory-kb** [comment]
@masskaneko さん、ありがとうございます。
どういった lint のチェックをするかはまた別途他の Issue で対応するとして、この Issue では textlint を GitHub Actions 上で動かせるように環境整えたら Pull request 出すように対応しようかと思います。

**Comment by yuhattor** [comment]
@masskaneko @bory-kb 
諸々ありがとうございます！
一旦 Close でいいですかね。
なにか残タスクあれば、Future Task として Issue に残そうかと思いますが
大丈夫そうですかね

**Comment by bory-kb** [comment]
>単語の対応だけに限って言えば、Translation Policy にはルールファイルのパスを指し示すだけでも良いかもしれません。ポリシードキュメントと定義ファイルの二重管理は面倒かなと思います。
ここは、皆さんの意見を聞きたいところですね

この辺りどこかでディスカッションしたいですね。
別の Issue としての扱いで良いと思いますのでこの Issue はクローズで良いと思います。

**Comment by masskaneko** [comment]
Textlint が走ったのを確認したらクローズしましょう。いまのところまだ走っていません。
トリガーが正しいか、lint の処理が走るかだけ確認できればよいと思います。
トリガーに問題があれば `workflow_dispatch:` をつけて手動で実行できるようにする手もありそうです。
