### ISSUE TITLE
textlint の rules.yml 拡充

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#28]
Translation Policy をもとに、以下の拡充をしたいです
https://github.com/InnerSourceCommons/jp-contents/blob/main/textlint/rules.yml

@bory-kb さんとか、いかがです?

**Comment by bory-kb** [comment]
やります！

**Comment by yuhattor** [comment]
お願いしますー！！

**Comment by bory-kb** [comment]
# 対応予定

- コントリビューション / 貢献 → コントリビューション
- リポジトリ / レポジトリ → リポジトリ
- 単体テスト / ユニットテスト → ユニットテスト
- InnerSource / インナーソース → インナーソース
- ドキュメント/文書 → ドキュメント
- 全角かっこ（）/ 半角かっこ () → 半角かっこ ()
- ユーザーやプログラマーなど頻出カタカナ英語の長音 (例 : ユーザではなくユーザー)

情報元
https://innersourcecommons.notion.site/2022-07-25-Getting-Started-with-InnerSource-5d2a1bdebeb842b197af8b16edadc91c


# 確認しておきたいこと
- 👆の情報元である Notion では InnerSource はカタカナでインナーソースとすると記載がありますが、 [Translation Policy 訳語の統一](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRANSLATION-POLICY.md#%E8%A8%B3%E8%AA%9E%E3%81%AE%E7%B5%B1%E4%B8%80) には 「InnerSource (インナーソースではない)」とありアルファベットでの表記が正となっています。アルファベットかカタカナか、どちらにすべきでしょうか？ (バグバッシュでこの辺方針が決まったりしたのでしょうか？)

- PayPal などの社名や何度も登場する人名なども rules.yml で指定したほうがいいですかね？ (社名はやってもいいと思いますが人名は First Name と Last Name の指定方法などややこしそうです) 参考 : [Translation Policy 人名と社名](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRANSLATION-POLICY.md#%E4%BA%BA%E5%90%8D%E3%81%A8%E7%A4%BE%E5%90%8D)


# 今回は対応しないであろうこと
- [全角語句と半角語句の間](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRANSLATION-POLICY.md#%E5%85%A8%E8%A7%92%E8%AA%9E%E5%8F%A5%E3%81%A8%E5%8D%8A%E8%A7%92%E8%AA%9E%E5%8F%A5%E3%81%AE%E9%96%93)
rules.yml だと上手いこと指定できなさそうなため。 (全角語句と半角語句の判断が難しそう)
- [句読点](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRANSLATION-POLICY.md#%E5%8F%A5%E8%AA%AD%E7%82%B9)
一括でルール化してしまうと Node.js の . などで引っかかってしまうため。

**Comment by bory-kb** [comment]
カタカナ英語の長音は👇の textlint のルールを適用してあげれば解決できそうですね。

https://github.com/textlint-ja/textlint-rule-preset-foreign-language-writing/tree/master/packages/textlint-rule-kana-english-suffix-er

併せてこの辺りのルールも検討しても良いかもしれません。
https://github.com/textlint-ja/textlint-rule-preset-foreign-language-writing/tree/master/packages/textlint-rule-kana-english-suffix-re

https://github.com/textlint-ja/textlint-rule-preset-foreign-language-writing/tree/master/packages/textlint-rule-kana-english-suffix-y

**Comment by yuhattor** [comment]
いいっすね。
インナーソースに関しては、日本では InnerSource にしなくても良いと思います。
「インナーソース」で検索すると "InnerSource" が引っ掛かってくれないんですよね。

固有名詞のルールは入れ込まなくて良いと思いますが、PayPal はめちゃくちゃ登場するので1個くらい入れてもいいと思います。

**Comment by bory-kb** [comment]
>カタカナ英語の長音は👇の textlint のルールを適用してあげれば解決できそうですね。

この textlint のルールですが、どうもまだイニシャルの開発が終わってないみたいで npm にパッケージが存在しなくて適用できないですね。
カタカナ英語の長音を rules.yml で対応するには無理があるので今回この部分は対応はできないかもしれません。(ほかに方法がなければ)

**Comment by bory-kb** [comment]
とりま PR 立てました。
https://github.com/InnerSourceCommons/jp-contents/pull/30

**Comment by yuhattor** [comment]
いいですね。改めてみてみると paypal とかのルールはかなりスペシフィックな感じなので、もしかするといらないかもしれませんね...
とりあえず、運用して行って様子を見てみましょう！
Merged!
