### ISSUE TITLE
Translation Policy Suggestion

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#3]
翻訳ポリシーに関する気になったこと、提案など、こちらにまとめていきましょう

**Comment by yuhattor** [comment]
川口さん第一稿での例

- [ ] 人名は日本語にするか => する
- [ ] 社名(Paypal)と言語名はそのまま
- [ ] 英単語の左右のスペースは抜く
- [ ] JavaScript: The Good Parts のリンクは英語版原著のまま
- [ ] タイトルは未訳なので訳す
- [ ] 数字は半角のまま
- [ ] ですます調
- [ ] 人名は・(中黒)で区切る
- [ ] x, y and z は・(中黒)で区切る
- [ ] ぐらいのルールでやってみました (ed

**Comment by masskaneko** [comment]
議題といまの私の考えを列挙しました。

軽そうなもの:

- [ ] カタカナ英語に長音をつける (例: ユーザー or ユーザ) [長音記号のトリセツ【2分でわかる！日本語表記ルール】](https://manual-torisetsu.com/blog/3219/)
- [ ] section を節と訳す (例：以降の節で順に説明します。)
- [ ] 他のsection, chapterへのリンク箇所は、それらの和名が決まったときに書き換える
- [ ] InnerSource / インナーソース
- [ ] OSS / オープンソースソフトウェア
- [ ] コントリビューション / 貢献
- [ ] リポジトリ / レポジトリ
- [ ] 訳者まえがき
	- yuhattor が代表者として書いてその後に訳者一覧を載せるもよし、全員1文簡単に書くもよし

----

重そうなもの:

- [ ] レビュー方法
	- 今回の場合担当分量が少ないので①②…ごとに Pull Request を作る
	- 1人でも approve してたらマージしてよい
	- そんなに厳しくなくていいけど明らかにダメなときはちゃんと言う
	- 日本語として読みやすいか主観で判断する (簡単)
	- 意味的な誤訳がないかの確認 (ちょっと難しい)
	- 代替翻訳案の提示 (あるとうれしい) 概ね「こういう案もあるけど選択は訳者におまかせ」という趣旨のコメントになるはず。「こうしなさい」ではなく。

- [ ] 訳注の書き方

```
日本人に馴染みのなさそうなことの補足説明、関連する和書の追記など、日本人の読者にありがたそうなことを記載したいことがあるでしょう。そんなときにどう書けばよいでしょうか。
章の冒頭 `#` と節 `##` ごとに、最後にリスト形式で訳注を設ける方法が考えられます＊1。
訳注対象の本文に全角のアスタリスクと1からの通し番号をつけます＊2。

* 訳注
	- ＊1: こうすると本文と訳注が同じ画面におさまります
	- ＊2: 半角にすると斜体に解釈されるので全角を使います
```

- [ ] 機械翻訳(DeepL, Google翻訳)の扱い
	- 以前に出版社を通して訳本を出したときは「結果的に同じ訳になったのならよいが全面的にそのままはやめてほしい」と言われました
	- 概ね合ってるが、ひどい間違いをすることもある(文ごと抜ける、語句が抜ける、and/or がつなげているものが違う…)ので、結局原文をよく読む必要がある。
	- 文意が合っていて自然にも見えるが、DeepL臭い、かっこ悪いということはある

- [ ] textlint の採用
	- 日本語向けの lint ツール。ルールを記述し、それに文章が沿っているか確認できる。Node.jsで動き、npm でインストール、コマンドラインで実行。
	- [日本語の技術文書向けのルールセット](https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing)がある。デフォルトは厳し目なので採用するならゆるくする必要がありそう。

**Comment by yuhattor** [comment]
一旦、TRANSLATION POLICY に入ったので Close します。
第２回以降の Review の際には別途立てましょう
