### ISSUE TITLE
GitBook では footnote が効かない

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#31]
PR #29 で footnote `[^]` を入れて GitHub では本文と footnote を行き来できるのですが、GitBook では効きません。

[GitBook では footnote がサポートされていないそうです](https://www.markdownguide.org/tools/gitbook/)。

**Comment by masskaneko** [comment]
footnote-string-to-number というプラグインを使えば解決するかもしれません。
staging ブランチで試してみます。
http://mebiusbox.github.io/contents/gitbook/src/footnote.html

**Comment by yuhattor** [comment]
なんと.... ありがとうございます。 
staging ブランチは今の運用だと特に他で使ってないので壊しても全然良いので、いくつか試していただけるとありがたいです

**Comment by masskaneko** [comment]
gitbook.com ではプラグインが使えず、セルフホストする場合のみ使えるのかもしれません。
少なくとも book.json にプラグイン名を書いただけでは何の変化もありません。

**Comment by masskaneko** [comment]
インナーソース入門については #35 で直りましたのでクローズします。
今後 GitBook でリリースする他の訳書については、もっと優れた解決策が必要と考えます。
