### ISSUE TITLE
GitBook では heading へのリンクが効かない

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#32]
例えば `#継続的なテストと開発` という heading があります。そこへのリンクは GitHub では `ja.md#継続的なテストと開発` なのですが、 GitBook では `ja#natesutoto` となっています。ひらがなとカタカナだけが拾われて natesuto になっているようです。

[GitBook のヘルプで heading の項目を見ると、relative link をつける方法があります。 ](https://docs.gitbook.com/editing-content/rich-text#relative-links)ただ、Rich text のところに書いてあるので Markdown ではできないのかもしれません。

**Comment by yuhattor** [comment]
summary.md を作っている時に私も色々試行錯誤して試したんですが、relative link はタグでつけるしかなさそうです。
ちなみに、summary.md の左側の目次から、特定のページの特定の heading に飛ばすことはできませんでした。
GitBook の OSS のものだと、何かやり方はあるような感じでしたが、gitbook.com は少し厳しそうでしたね...

**Comment by yuhattor** [comment]
heading に飛ばす際は以下でできるみたいです。こうすると ja.md#where-open-source-principles-work の相対リンクでいけるとおもいます。たぶん...

```
## オープンソースの原則が機能する場 <a href="#where-open-source-principles-work" id="where-open-source-principles-work"></a>
```

**Comment by masskaneko** [comment]
相対リンクはこれで直りました。すばらしい。
今後、より大きな本を GitBook で出すときに知っておくべきことですね。
あとは同じく staging での確認が必要な #31 を直して PR を出そうと思います。

**Comment by masskaneko** [comment]
インナーソース入門については #35 で直りましたのでクローズします。
今後 GitBook でリリースする他の訳書についても同様の対応をとるのがよいと思います。
