### ISSUE TITLE
textlint の lint error がすべて解消されていない

### ISSUE THREAD

**Issue by bory-kb** [yuhattor/japanese-contents#33]
GitHub Actions で実行されている textlint のチェックが未解消です。

**Comment by bory-kb** [comment]
PR を立てたときなどに textlint が実行されますが、指摘事項が何点もあがっています。
[Translation Policy](https://github.com/InnerSourceCommons/jp-contents/blob/main/TRANSLATION-POLICY.md) に沿った形に修正しようと思います。

訳語の統一などは機械的に対応できるので問題ないと思います。
「一文に二回以上利用されている助詞 "と" がみつかりました。」や「一つの文で"、"を5つ以上使用しています   」などは一旦いい感じで修正してみようと思います。

**Comment by yuhattor** [comment]
いいですね！お願いします！

**Comment by masskaneko** [comment]
やろうと思っていて手つかずだったものです。ありがとうございます。
#34 で直りましたのでクローズします。
今後も error のない状態を保ちましょう。
