### ISSUE TITLE
リリース時のドメインを決定する

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#36]
fyi: @masskaneko 
getting-started-with-innersource-jp .innersourcecommons.org
とかは非常に微妙だと思います。
なにかいい名前ないですかね。

決定には、今後 Understanding ... の日本語訳をどこにホストするかという点も考慮する必要がありますね。
もしこれらの本が将来他の言語に翻訳される可能性を考えると、リポジトリの切り方も変わってきますよね

- 案1: 日本向けの GitBook コレクションを作って、全ての本を一つのドメインにまとめる。
  - jp-books.innersourcecommons.org/getting-started-with-innersource
  - jp-books.innersourcecommons.org/understanding-the-innersource-checklist
  - jp-books.innersourcecommons.org/adopting-innersource
- 案2: Getting Started with InnerSource は一つの本としてまとめる。国際化対応も今後同一ドメインにぶら下げる。
  - getting-started-with-innersource.innersourcecommons.org/jp
  -  getting-started-with-innersource.innersourcecommons.org/en
  -  getting-started-with-innersource.innersourcecommons.org/fr

その他、アイデアありますか？

**Comment by masskaneko** [comment]
これは GitBook のカスタムドメインの話ですよね。

すでに原著も日本語版も GitBook でリリースされているインナーソースパターンではこうなっています。
- 原著 https://patterns.innersourcecommons.org/
- 日本語版 https://patterns.innersourcecommons.org/v/jp/ ( `/v/jp/` がついている )

これに合わせるならインナーソース入門は
- https://getting-started-with-innersource.innersourcecommons.org/v/jp/

になるのですが、Getting Started with InnerSource は原著が PDF なので、合わせる対象がありません。

ただ、案1 にするなら
- jp-cooks.innersourcecommons.org/

という日本語版の一覧ページがあることが望ましいと思うのですが、そうすると原著の一覧ページである次の URL とずれます。
- https://innersourcecommons.org/learn/books/

なので、案2 が良いと思います。

**Comment by masskaneko** [comment]
できれば本件と合わせて、個々の原著のページから日本語版へのリンクを貼りたいですね。
いま、インナーソースパターンは日本語版があることが原著のページを見てもわからないので。

- https://innersourcecommons.org/learn/books/innersource-patterns/
- https://innersourcecommons.org/learn/books/getting-started-with-innersource/

`#marketing` チャンネルに書けばどなたかサポートしてくださるのでしょうか？

**Comment by yuhattor** [comment]
@masskaneko marketing で、サポートしてくれると思います！！

**Comment by yuhattor** [comment]
@spier 
I would like to hear your opinion. We need to decide on a DNS name for the O'Reilly translation of "Getting Started with InnerSource".

Right now, I'm thinking of the following form.
1. jp-contents.innersourcecommons.org/getting-started-with-innersource
1. getting-started-with-innersource.innersourcecommons.org/v/jp/

After discussion, we thought idea 2 was appropriate if the format was to be adapted to other ISC resources. This would allow people from other languages to contribute to the translation.
However, we are very keen to increase the number of contributors to jp-contents as a TC.
In this translation, @masskaneko has really made a great contribution. (By the way, he will be leading the "Understanding the InnerSource Checklist" translation project next time!!!) But not that many people actually contributed as code after initial translation. In order to onboard long-term contributors to the repository, we need a repository that is somewhat cohesive.
It makes sense for Japanese contributors to work collectively in a repository called jp-contents.

So we think jp-contents would be a good domain to go along with it.
Then we need to have DNS settings for **jp-contents.innersourcecommons.org**

What do you think?
Also, I want to ask, how long do you think it would take to set up DNS? I'm assuming it will take at most 2 days to reflect.

**Comment by spier** [comment]
@yuhattor I need to clarify one question first, as I think it might become a blocker for your the publishing approach with gitbook:

It sounds like you want to maintain the translations for all 3 books in a single repository?

I am not sure if that will work with gitbook. gitbook requires the `.gitbook.yaml` to be placed in the [root of the repo](https://docs.gitbook.com/integrations/git-sync/content-configuration#configure-a-specific-synchronization). That means that you cannot publish separate books (with different subdomains) from the same repo.

What you could do is to publish all translations as a single book but that would lead to a really large and potentially message table of contents. So I suspect that is not desirable either?

Let's clarify this first, before picking the subdomain and URL pattern for the translations.

**Comment by yuhattor** [comment]
@spier 
We hope to eventually offer O'Reilly books in formats such as pdf and epub. Ideally, the Japanese pdf would appear on the innersourcecommons.org page translated into Japanese.
Therefore, we do not consider the gitbook to be the final form. Also, since we have official permission from O'Reilly this time, we would like to be a little more particular about the format. For that reason, we do not think markdown is the best choice, at least not yet. I think asciidoc might be better.

So in any case, we think it is a good idea to gather contributors to jp-contents. I'm thinking of using this as a starting point to separate publications into their respective formats.

What I'm thinking now is to create a Japanese Book collection for the ones to be published in gitbook, and tie several GitBook style spaces under it.
This operation could use the same mechanism as innersource patterns.

How about this...?

**Comment by spier** [comment]
hi @yuhattor.

_**Early warning:** 
DNS changes for innersourcecommons.org take a bit of time.
You mentioned a goal of Oct 15th. In order to be ready for that date, we should start the process pretty soon._

So to your case above:

I understand that you want to create a new gitbook Collection, and then group multiple spaces under it.
I don't know if they approach we used for the InnerSourcePatterns repo will work here. We can try though :)

I suggest to create the desired gitbook setup first.
Do you need help with that?

Once that is ready, I can help you to request the desired DNS change.

**Comment by yuhattor** [comment]
@spier 
Taken offline further
