### ISSUE TITLE
Retrospective: "インナーソース入門" 翻訳の振り返り

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#43]
インナーソース入門 (Getting Started with InnerSource) の翻訳が終わりました。
どのような形でリリースするかという課題 #36 が残っていますが、翻訳自体は完了しています。
また、新たに [Understanding the InnerSource Checklist](https://innersourcecommons.org/learn/books/understanding-the-innersource-checklist/) の翻訳を私がリードして始める予定です。

その前に、インナーソース入門にコントリビューションしてくださった方々が翻訳の振り返りをして、今後より良い活動ができるようにしたいと思います。

## 振り返りの方法

以下の問い (一部でもよい) への答えをこの Issue のコメントとして書いてください。2022/09/18 まで。
答えは主観的なものでかまいません。根拠があれば明示することを推奨します。

* 何が良かったか(or 悪かったか)？それはなぜか？より良くするには？
* 続けたいこと、やめたいことはあるか？それはなぜか？
* 何を学べたか？
* 期待していたことと実際の差はあるか？

コメントが集まった後、それを分析してまとめます。2022/09/21 まで。
この次点でこの Issue をクローズします。

そして、Understanding the InnerSource Checklist の翻訳プロジェクトを始める際、この振り返りをもとにした案を私から提示し、翻訳メンバーと議論して改善策を確定させようと思います。翻訳プロジェクトについては、別の Issue および Slack にて案内する予定です。

**Comment by yuhattor** [comment]
### 良かったこと (続けたいこと)
- 多くのメンバーが InnerSource について学ぶことができた
- jp-contents のリポジトリや、GitBook の運用をはじめとして、日本側にも知見がたまってきた
- インナーソースの活動について、アップストリームに対してもインパクトを示せた
- jp-contents の TC が増えたことに加え、活動を通して少しずつ活動が軌道にのってきたように思います。 (もっとコントリビューター・インナーソースの伝道師を増やしたいです！)
- textlint や markdownlint など、活動を今後進めるのに対して基本構成ができてきた
- 翻訳活動を通じて、インナーソースの志のあるメンバーが繋がれた
- オライリーメディアなどと連携をとり始める起点にできた。
- Andy Oram さんからもメッセージをいただけた！
- 多くの方が、オライリー本の翻訳を行えた

### 今後もっと良くするには 
- TC の @masskaneko さんの作業が重かったかも。もっと分散できたら良いかもしれないですね。
- スケジューリングはもう少しちゃんとひいた方が良かったかもしれません。
  （同時にスケジュールをしっかりひくと"タスク感" "やらされている感" が強くなって自由度が減ってしまう可能性もあるか?）
- もっと Issue を細切れにして、だれかが取っていけるような環境は必要だったかもしれません。
- 参加者以外もどんどん新しく入っていける環境が欲しい
- Issue や PR により早く反応できるようにしたい。
- GitHub に慣れていないメンバーのオンボーディングもしたい。
- コミュニティに新しく入った人が、自分の役割をもっと簡単に見つけられるようにしたい
- 表現の統一などを含め、監訳はおいた方が良いかも。
- クオリティを高くするのは少人数でやった方が良いと思いますが、一方で InnerSource Commons としての翻訳活動は「インナーソースコモンズの活動へのオンボーディング」の意味もあると思っています。多くの方に参加していただける枠組みは残したいです。「翻訳メンバー」だけでなくそのほかの役割も定義して、一人ひとりがコミュニティにインパクトを出せるようにしたいです。
  

### 続けたいこと
- 参加者が楽しんで議論をできるオープンな環境
- ちゃんとチェックなどの自動化がされていること
- 議論がされること (Trsuted Committer などの議論)

### やめたいこと, Why
- 今後もっと良くするには に記載(悪かったこと含め)

### 学べたこと, Why
- インナーソースについてより深く学べました
- 翻訳について、表現の観点で @masskaneko さんをはじめ、多くの方にレビューいただいたところは大きい学びでした。
  やはり自分の口癖や、断定せずに中庸な表現をえらんでしまうこと(それで結局内容がぼやける) など、文章を書く上で注意するべきことが多かったなと思います。

### 期待とのギャップ
- ポジティブなキャップしかありません。もっと少人数でやるのかなと思っていましたが、多くの方に参加していただき、コミュニティとしても成長できました。


---
「やめたいことはあるか？」「悪かったか」に関しては「今後もっと良くするには 」にまとめました。
気づいたことがあれば Update します！

**Comment by uikou** [comment]
私翻訳をしたわけではないので、ここに書くのは烏滸がましさでいっぱいなのですが…。

**よかったこと**
* エンジニアではない（Marketing）側の人間の私が、どうしても理解できない部分がありますが、チェックするという機会に恵まれたことで、さらっと読んだ場合ならば見過ごしてしまうことについて内容を理解することができた。
* 体裁チェックなど、技術的じゃない部分での貢献ができるかもということがわかってちょっとほっとしました。

**今後もっと良くしたいこと(主に自分に向けて)**
* やはり実践を伴わない、非技術者である自分が理解するためにはもう少し気合が必要。非技術者側の人間でも理解できるように噛み砕くことが貢献できることと改めて心得たい。
* エンジニアじゃない私が入っても何かできることあるのかしら〜と一歩引いてしまっていたけれど、できることについてもっと積極的に探していきたい。

**続けたいこと**
以下の服部さんの意見に大賛成！
> ・参加者が楽しんで議論をできるオープンな環境
> ・ちゃんとチェックなどの自動化がされていること
> ・議論がされること (Trsuted Committer などの議論)

**学べたこと, Why**
* インナーソースについて強制的にどういうものだろう？ということを考える場をいただけたおかげで、ではこれは技術者じゃない側はどういうことなのだろうということを考え始めました（これからですが）
* 文章ルールについてはメインのライターの方ではなく、私みたいな人間が校正する分業にしたらより作業を効率化できるのではないか

**期待とのギャップ**
自分がもっと勉強しなきゃな〜というのにつきます。

以上、偉そうですが…！！今後もよかったら引き続きよろしくおねがいします。

**Comment by amixedcolor** [comment]
何が良かったか(or 悪かったか)？それはなぜか？より良くするには？
---
最後にみんなでこここうするといいかもポイントを上げていったのがよかった
単純なtypoや表現の統一ができていない箇所に気づける
もう少し時間をとって同じ箇所を複数人が確認したようにしたい

続けたいこと、やめたいことはあるか？それはなぜか？
---
これ自体を続けたい
インナーソース自体を学べる上に翻訳の経験と、コミュニティを立ち上げていく経験ができるから

何を学べたか？
---
インナーソースとはなんなのか

期待していたことと実際の差はあるか？
---
想像よりも負担が少なく、取り組みやすかった

**Comment by shrimp78** [comment]
### 何が良かったか
- 普段、翻訳活動というものには全く接点がなかったが、実際に関わり翻訳にチャレンジすることで多くの新しい発見や、難しさなどを学ぶことができた
※本筋とは思いっきり外れるんですが...　たまに海外本の日本語訳版なビジネス書を読んでいると、全然頭に入ってこない時とか多々あり、やはり日本人にとって本当に読み易い文章に変換するという作業がいかに大変なのかを身をもって学びました...
- InnserSource自体も学べたこと、またこの活動に関わる方々と繋がりをもてたこと

### 続けたいこと、やめたいことはあるか？それはなぜか？
- Understanding the InnerSource Checklistも取り組みたい

### 何を学べたか？
- Bug bashについても（個人的に）初めての取り組みだったが、学びが多かった
  - 楽しかった :) 
  - 「Slackやprの中では触れなかったけど、ちょっと軽く聞きたい質問」などについては、オンラインで集まっている事でカジュアルに問いかける事ができて非常に生産性が高かった
  （これは、良かったこと・続けたい事に入れる話かも・・）
  - 翻訳はChapter事に分業で実施していたものの、別の人の文章も強制的に読む良いきっかけになった
   
### 期待していたことと実際の差はあるか？
とくにありません！！

**Comment by bory-kb** [comment]
## 良かったこと (続けたいこと）
- 翻訳を通して同じ部分を何回も読んだりしてたのでその分理解が深まったと思えたこと (どこかで話す時にもある程度自信持って話せそう)
- GitHub Actions で textlint のチェックを都度実行し、一貫性を保つ取り組みができたこと
- 全体としてより良くなるように何かアクションすること (例 ：気になるところを Issue としてあげる 、Issue のディスカッションに参加して発言してみる)
## 学んだこと
- 原文の意図するところを崩さず訳すことの難しさ (個人的にはこれに尽きます)
## 期待してたこととの差
- 特に思いつかないです

**Comment by masskaneko** [comment]
ありがとうございます。私も共訳者として振り返ります。

## 何が良かったか(or 悪かったか)？それはなぜか？より良くするには？

- 翻訳をきっかけにインナーソースを知る人が増えたことは良かった。これからも増やしていきたい。
- 翻訳を初めて経験した人が増えたことは良かった。ときどき、年に2-3回くらいこうした機会があってもいいと思う。
- TC になって全体の品質を見たり、ルールを策定したり、さらにはコミュニティの今後を考えたり、リードする機会が得られたことは良かった。今後もインナーソースの探究と普及のために継続したい。
- 技術書における英日翻訳の品質は英・日・技術の知識による。というのは以前に共訳したときも結論づけたことであり、今回もそうであったと思う。おそらく訳者によって英・日・技術のどこが得意かそうでもないかがあって、それが訳文に現れていたように思える。次回の翻訳では質を強化していけるレビューに取り組みたい。そのためには PR を受け入れる条件、訳文に求められる質、TC の役割と TC になる条件を明文化する必要があると考える。質の平均化、意味と用語の整合性のための監訳も必要と考える。
- 初期コミットに DeepL の訳が載っていたせいか、それをベースとした訳文になっており、訳者の能力とオリジナリティを制限してしまったように思える。次回は DeepL の訳を載せることはやめ、DeepL のような機械翻訳をどう使うべきか、使わないべきか指針を示したい。
- lint を GitHub Actions として実装できたのは楽になって良かった。ルールの採否は道半ばなので洗練させてゆきたい。
- ライセンス確認とリリース形態決定は純粋な翻訳以外の重要なタスクであることがわかった。いまこれを @yuhattor に全て頼っていることは継続性に問題があり、他にもできる人を増やしたい。InnerSource Commons サイトの国際化方法が固まれば、リリース形態決定についてはそれほど悩まなくて済むようになるかもしれない。

## 何を学べたか？

- 日本コミュニティ参加前からインナーソースには継続的に探究する価値があるものと確信していた。日本コミュニティが立ち上がってこの翻訳に沢山の人が貢献する様を見て、その確信が強くなった。
- これまでもいくつかの技術コミュニティの黎明期を経験した。それらがうまくいくかは少数の熱意によるところが大きいと結論づけており、今回もそうであるとわかった。この熱を保てるような活動をしていきたい。
- この本は発刊当時に読んだのだけど、覚えていたのは PayPal の事例で、オープンソースのくだりは完全に忘れていたのでよい復習になった。

## 期待していたことと実際の差はあるか？

- 2-4人しか集まらないだろうと思いきや、もっとたくさんの人が関わった。やはりインナーソースにはそれだけの可能性があるのだ。
- 以前に手掛けた共訳ではレビューを念入りにやったので、今回はカジュアルにマージされたように思えた。上述の通り、今後は質を強化していけるレビューに取り組みたい。
- 訳者ではない方々を交えての Bug Bash は私には全くなかったアイデアであり、価値があることがわかった。
- InnerSource Commons は国際コミュニティなので、より多くの日本人が国際的な議論の場に出ることが望ましい。だが、翻訳を振り返ると国際的な交流が **不可欠な** 場面は稀に思える。より難しい概念、完成度の低い概念を翻訳するときには、著者や識者のいるチャンネルでの議論が必要になるかもしれない。

**Comment by masskaneko** [comment]
振り返りに参加してくださって皆様、改めてありがとうございました。
達成できたことが何かコメントから考えると、訳書ができたことはもちろん、そのプロセスが確立され、コミュニティが醸成されてきたこと、そして参加者がインナーソースを知ることができたことではないかと思います。

また、そのプロセスとコミュニティをどう洗練させてゆくかという意見も生まれました。レビュー、監訳、自動化ツール、新たなメンバー・TCを増やす仕組み、原著者と出版社との関係づくり、国際的な場での日本のプレゼンス向上、という点が挙げられています。

Understanding InnerSource Checklist には、インナーソース入門(Getting Started with InnerSource) よりも汎化された記述があり、分量もやや増えていますので、翻訳を通じてより深い理解が得られるでしょう。

以上を鑑みて、Understanding InnerSource Checklist 翻訳を募る案内を近日中に出します。
