### ISSUE TITLE
10月18日リリース前の最終確認事項

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#47]
- [x] GitHub Repository のストラクチャー整理
- [x] ロゴの変更
- [x] 最終リントチェック
- [x] README の整備
  - [x] GitHub Actions リリースフローの図示
  - [x] ページについての解説
  - [x] パイプラインの Health 確認バッジ追加
- [x] ブランチプロテクション (Home, Getting..., Understanding)
- [x] コンテンツの最終確認
  - [x] TC @yuhattor の最終確認
  - [x] TC @masskaneko さんの最終確認 
- [x] ドメイン / Path 関連
  - [x] ドメインのルールとパスのチェック #36 
  - [x] GitBook の DNS 割り当て #36
  - [x] [GitBook の ストラクチャー確認](https://innersourcecommons.slack.com/archives/C03P1MVMBRS/p1664030938471039)
- [x] GitBook の Staging 環境作成
  https://innersourcecommons.gitbook.io /jp-contents-staging/ (Unlisted な staging がクローリングされないようにスペース開けてます。staging ブランチに更新ください)
- [x] CODEOWNER の Path 設定を編集 (現在、Path として割り振られているものを解除。Getting... のみから全体へ。)
- [x] @masskaneko さんを Maintainer に Update (GitHub: staging のブランチの削除など含め、やっていただければありがたいです。)
- [x] GitBook 確認環境への権限付与 -> TCs

**Comment by yuhattor** [comment]
[こちら](https://jp-contents.innersourcecommons.org/)にリリースしています。

**Comment by masskaneko** [comment]
Sebastian から GitBook の権限をもらいましたので `GitBook 確認環境への権限付与 -> TCs` は終わっています。これで本件は全て終わりではないでしょうか。

**Comment by yuhattor** [comment]
終わりですね！Close しましょう！
