### ISSUE TITLE
Getting Started with InnerSource の表紙/ライセンスの明記

### ISSUE THREAD

**Issue by yuhattor** [yuhattor/japanese-contents#53]
Getting Started with InnerSource の表紙をオライリーのものではない日本版を作る必要があります。
同じタイミングで、O'Reilly Media からの翻訳の許可とライセンスについて明記したいです

**Comment by masskaneko** [comment]
https://jp-contents.innersourcecommons.org/v/getting-started-with-innersource/
このリリースにある通り、日本語版の表紙を設け、翻訳許可とライセンスについても記述しました。クローズします。
