### ISSUE TITLE
Understanding the InnerSource Checklist の邦題を決める

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#60]
この翻訳プロジェクトが始まる前に "詳解インナーソースチェックリスト" という名前がついていました。
ですが、これは決定されたものではなく、ふさわしい邦題を考えましょう。

**Comment by masskaneko** [comment]
一番考えなければならないのは、この本がチェックリストかどうかではないでしょうか。
この本では最後になって初めて Appendix として The Actual Checklist が登場します。本文にはありません。
また、それもチェックリストといえるほど各項目の実施有無を簡単に確認できるかというと違うと思います。

- [ ] こういう
- [ ] ものでは
- [ ] ないわけです

Appendix は **要点の箇条書き** ではないかと考えます。
要点というのは、インナーソースを実践する前に満たしておくべきことの短いまとめです。

そして、要点を定めている理由を理解するために本文があるのだと思います。
また、本文はインナーソースの意義と方法の概略を説明するものであり、インナーソース入門(Getting Started with InnerSource)と同じく入門書の扱いではないかと思います。

とすると、本書の邦題としては、例えば
**続・インナーソース入門 ～意義の理解と要点の確認～**
が考えられます。

ほか、ご意見おまちしてます。

**Comment by yuhattor** [comment]
上は、最初に仮でつけたんですが、 O'Reilly の "Understanding the ..." 系の本に習ったものでした

Understanding and Using C Pointers: Core Techniques for Memory Management
→ 詳説 Cポインタ

Understanding the Linux Kernel: From I/O Ports to Process Management 
→ 詳解 Linuxカーネル

など。オライリー本は「詳解」が付いていることが多いので。
これに倣う必要はありませんが、一応仮で名付けた背景としてはこんなところでした。

**Comment by yuhattor** [comment]
一方で「詳解」シリーズで言うと
詳解 OpenCV 3
→Learning OpenCV 3
詳解 シェルスクリプト
→ Classic Shell Scripting

ですから、「詳解」も 1:1 の関係で使われるわけではないと思います。

ただ、個人的な思いとしてはせっかくオライリーの本を訳しているというのもあるので、
オライリーの諸々の本に命名を寄せたいとは思いました。

従来のオライリーの読者にも手に取ってもらいやすいですし、
インナーソースコモンズオリジナルなものではなく、ちゃんと「オライリーの本」として読んでくれるかと

と言う意見です

**Comment by masskaneko** [comment]
これまでのオライリー本の邦題に習おうとしたのですね。
新しい視点でした。これは考えどころですね。ありがとうございます。

詳解または詳説と冠されている本の原題とページ数を調べてみました。
https://www.oreilly.co.jp/catalog/

| 邦題 | 原題 | ページ数 |
|----|----|----|
| 詳解 シェルスクリプト | Classic Shell Scripting | 345 |
| 詳解 Linuxカーネル | Understanding the Linux Kernel | 1024 |
| 詳解 システム・パフォーマンス | Systems Performance | 784 |
| 詳解 Open CV 3 | Learning OpenCV 3 | 992 |
| 詳解 ビットコイン | Grokking Bitcoin | 504 |
| 詳解 インシデントレスポンス | Applied Incident Response | 480 |
| 詳説 正規表現 | Mastering Regular Expressions | 528 |
| 詳説 Cポインタ | Understanding and Using C Pointers | 248 |
| 詳説 イーサネット | Ethernet: The Definitive Guide | 536 |
| 詳説 Deep Learning | Deep Learning | 608 |
| 詳説 データベース | Database Internals | 392 |

これを見ると、原題に Understanding がついているから詳解 / 詳説 と題されるわけではないように見えます。
また、ページ数をみると、これらの本は詳解 / 詳説と呼ぶにふさわしい量があるように見えます。

一方、Understanding the InnerSource Checklist の量は60ページであり、上記の本に比べるとかなり少ないです。
Adopting InnerSource は158ページあり、むしろこちらの方が詳解に値するのではないかと思います。

オライリー本らしい邦題にしたい！という思いには同意しますが、それが詳解または詳説かというと違うかな？というのが今の所感です。オライリー本らしい邦題がどんなものか、また時間をとって調べてみようと思います。Building Micro-Frontends が単に [マイクロフロントエンド](https://www.oreilly.co.jp/books/9784814400027/) になっていたりするので、"インナーソースチェックリスト" だけでもいいかもしれませんね。

**Comment by yuhattor** [comment]
おまとめありがとうございます！

悩ましいですね。 たしかに、詳解ほど解説されてませんしね。
詳解だと、60ページじゃ物足りないよなというのは同意です。

> "インナーソースチェックリスト" だけでもいいかもしれませんね。
そんな気もしてきました。

**Comment by masskaneko** [comment]
今のところ以下の考えです

- 単に "インナーソースチェックリスト"
- 副題をつけるなら "インナーソースチェックリスト ～実践事例から得られた成功の要点～"
