### ISSUE TITLE
books 以外のコンテンツの拡充

### ISSUE THREAD

**Issue by bory-kb** [yuhattor/japanese-contents#61]
InnerSource Commons として公式に出しているコンテンツは books ディレクトリ内で翻訳プロジェクトとして活動していますが、そのほかにも InnerSource に関する有益なコンテンツは多数あると思います。
これらも日本語へ翻訳する価値があると思いますので、その提案です。

上記でいうところの books 以外のコンテンツは書籍としての形式ではなく一枚もののドキュメントだったり、パワーポイント等のスライドだったりするので books ではなく別途 docs というディレクトリを切ってその中で管理するのが適切だと考えます。

第一弾として [opensource VS innersource](https://tech.europace.de/post/europace-inner-source-prinzipien/) などいかがでしょうか。
（リンク先の資料はドイツ語のようですが英語版を服部さんからもらったのでこちらの日本語化）

**Comment by bory-kb** [comment]
とっかかりとして上記 opensource VS innersource の諸々下準備の PR を投げました。👇
https://github.com/InnerSourceCommons/jp-contents/pull/62

@yuhattor @masskaneko 
このあたりご意見いただけないでしょうか？
（もし他に一緒にできそうな方いらっしゃったらメンションいただいたり…）

**Comment by masskaneko** [comment]
アクティブな提案！
候補を考えましょうか。すぐ思いつくものだと State of InnerSource Survey です。
https://innersourcecommons.org/learn/research/state-of-innersource-survey-2021/
books が入門〜基礎なのに対して、Survey は実践者の感想と流行を示すものなので実際どうなのかを日本人が知る良い情報源ではないかと思います。

opensource vs innersource は内容は良いかもしれませんが、InnerSource Commoms のコンテンツではなく Europace 社のコンテンツに見えるので、この場でやるものではないかも？と思えました。ぱっと見ではそうなんですがどうなんでしょう？

**Comment by bory-kb** [comment]
State of InnerSource Survey もいいですね！
権利も InnerSource Commons にありそうですし、その辺もスムーズに進められそうです。

権利周りつながりだと opensource VS innersource も許可はもらってるはずですが、 @yuhattor さんがこの辺り直接やりとりしてくださってるはずなのでお聞きしたいところですね。

**Comment by yuhattor** [comment]
すみません、レスしたつもりができていなかったようです...

諸々ありがとうございます！
Europace 社の Isabel (ISC President)からも了解を得ています👍 
こういったリソースは有益なので日本語にして増やしていきたいと思っています。

ただ、リポジトリ的にはどこでやるのかが少し悩ましいところです。
そもそも State of InnerSource Survey は Git で管理できないですし。
あとは、小林さんのプレゼンも英語にしたいなと思ったりしています。

少なくとも ISPO を始めようとした時に、社内で InnerSource の活動をカンタンに始められるキットがないのが問題だと思うのでそこにアプローチしたいんですよね。

awesome-innersource はとっても良いと思いますが、一方でこのリポジトリは「リンクの掲載」を目的にしているので、GitHub 上でコンテンツを載せる時には不足するなと思っています。
https://github.com/InnerSourceCommons/awesome-innersource

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-roadmap

@masskaneko @bory-kb 
たとえばこれ、最初日本ように使おうと思ったんですが、リポジトリ名ごと "community-kit" みたいなものに変えてしまって
日本からテンプレートとか ISPO 用のリソースをまとめて使えるようにしてみるのとかはどうでしょう。

ロードマップはロードマップとして残すとしても、コンテンツがあった方が継続的にコントリビューションできそうかな...と
