### ISSUE TITLE
Understanding~ Supervising Level of Translation Items

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#68]
Listing up all supervising level of translation items in Understanding the InnerSource Checklist to make it cohesive.

- [ ] 本書内リンクの書き方
- [ ] 本書外リンク先の存在確認
- [ ] 参考文献と訳注の書き方
- [ ] TL;DR の表記
- [ ] TL:DR の語調 (ですます or だである)
- [ ] トラステッドコミッター の表記
- [ ] 部族的知識 or 部族内知識
- [ ] passive documentation の訳
- [ ] documentation の訳
- [ ] (ドキュメントの) findability の訳
- [ ] ドキュメント or 文書 (揺れていても良いか統一するか)
- [ ] コントリビューション or 貢献 (揺れていても良いか統一するか)

**Comment by yuhattor** [comment]
- [ ] TL;DR における口調「ですます」か「だである」か
