### ISSUE TITLE
Understanding~ Integration Review: 0-forward

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#78]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1#L6-L7

> オープンソース由来の方法を応用して PayPal 内の壁を壊し、協働を引き起こしてきた一連の旅路を公開する

が2つの文に重複していて必要なく思える。

- この発表はその意志の表れなのです。

でよいのでは

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1#L5

主語の後に句点を入れたほうがよい程度の長い文に思えます

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1#L11

この本に詳細は登場しませんが、データサイエンスに基づいたテクニカルな方法を知りたいですね。
例えばサイロがどれだけあるのか、取り払われたのかを定量化する方法が相当するのだと思います。

**Comment by yuhattor** [comment]
> が2つの文に重複していて必要なく思える。

同様のことを思いました。
「この発表がその意図を示しています。」とか、言っていただいたように「この発表はその意志の表れなのです。」とかでいいかもです。

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1#L10

ちょっとスッと入ってこなかったです
「文化的な進歩を成すためのツールとプロセスを設計する能力のあるチーム」
の言い換えとして、以下を考えてみました。

- この成果は、文化的な向上を促すツールやプロセスを構築する才能を持つチームの貢献によるものだと言えます。
- この旅の成功は、文化的な発展に貢献するツールとプロセスを構築できるチームの存在が大いに関係しているでしょう。

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/0-foreword.md?plain=1#L17

いきなり口調が変わっている感じがします。以下のような言い換えはどうでしょう。

- 皆さんがこの本を楽しみ、新たな知見を得ることができることを願っています。
- 願わくは、皆様がこの本を読んで楽しみながら、有益な知見を得られることを願っています。
- 皆様にこの本をお楽しみいただき、知見が得られることを心から願っています。
