### ISSUE TITLE
Understanding~ Integration Review: 1-Why InnerSource~

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#79]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L94

公式コピーについて、Copy というのは英語的な表現なので、何か他にした方がいいかもしれません。
複写とか、原稿、みたいな本来のものも考えられますが、ここは「公式版の書籍も出版しています」とかでもいいかもです

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L103

リンク切れ起こりそうです

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L134

「私にないもの」
ではなく「オープンソースにあって私がもってないものは何か」のような方がわかりやすいかもわかりません。
「オープンソースにあるが、現場にはないもの」
とかはどうでしょう。ちょっと意訳な感じがありますが

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L158

欠陥密度がわかりづらかったです。「ソフトウェアコードの行数あたりの欠陥数」のように意味をそのまま書いてもいいかなと思いました。これってよく使う表現ですかね

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L225

ビジュアルソース でしょうか

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L236

リンク切れを最後に治した方が良いかと思います。
「インナーソースの定義や標準の作成し」👉「インナーソースの定義や標準を作成し」

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L314

リンク切れが心配です

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L318

```
Coverity 静的解析年次レポート: 最新版は [“Coverity Scan Report”](http://bit.ly/2o3g7O6) を参照
```

ただ、リンクは切れています。
http://softwareintegrity.coverity.com/rs/appsec/images/2013-Coverity-Scan-Report.pdf

**Comment by masskaneko** [comment]
- [ ] 本書内リンクの書き方
- [ ] 本書外リンク先の存在確認
- [ ] 参考文献と訳注の書き方

これらは本書全体的にみましょう。#68 の項目としておきました。Integration Review はいい機会なので↑のようにコメントしていきましょう。

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L110-L111

「この本に」 「ここで提案」 という、似たような書き方の文が並んでいるので原文でもそうなのかと確認してみると、意味が違っているのではないかと思えました。私の解釈した意味を日本語にするとこうです。

- 本書に記された私達の経験を読むことで、小さな変化がより大きな文化の変革へと繋がることを追体験していただきたいと願っています。
- そのために重要な変更マネージメントの方法も本書で説明しています。

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/1-why-innersource.md?plain=1#L91

にある通り、この本は経験談です。
なので、`as we go on this journey` は、「本書に記された私達の経験を読むことで」 と解釈できます。
また、`We hope ... you will see` は、「追体験していただきたいと願っています」 と解釈できます。「理解していただきたい」でもよいでしょう。

2文目の`change management`は「変更マネージメント」「変更管理」の意味ではないかと思えました。
本書では Pull Request を活用したコラボレーションの重要性とテクニックがたくさん述べられているからです。
