### ISSUE TITLE
Understanding~ Integration Review: 3-The Most Important Role~

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#81]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1

**Comment by yuhattor** [comment]
自分の書いた章なので、他の方、レビューお待ちしております！

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L66

ゲートキーパー→門番とかの方が良いですかね?

**Comment by yuhattor** [comment]
fyi
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L93
リンク切れ..

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L120

"Passive Documentation" は両方大文字で用語なので、このままにする方が良いと思います。
そうしたら "パッシブ・ドキュメント" ではなく "パッシブ・ドキュメンテーション" にした方が良いかもですね。

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L14

誤字：リファクタリング

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L54

"他領域 **から** のコントリビューター" の方が、他領域から自領域へコントリビュートしようとしてることがわかりやすいのでは。

**Comment by masskaneko** [comment]
感想：
[> さらに、トラステッドコミッターはメンタリングの時間を使って、次の大きなリファクタリングに備えた素晴らしいドキュメントを作成することがわかりました。](https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/3-the-most-important-role-and-the-first-step-trusted-committer.md?plain=1#L113)

メンタリングの時間でドキュメントができるのは不思議でした。
もちろんこれが本当なら素晴らしいことなんですけど、教えることがほとんどであろうメンタリングの時間でドキュメントができるのかな？と。
コントリビューターから質問されたことが今のドキュメントに足りないことだと気づけるという意味ならわかります。

**Comment by masskaneko** [comment]
感想：
インナーソースについて読む本としてこれが初めてで、トラステッドコミッターという役割を知るにも初めての人が、この章をどこまで理解できるか想像してみました。
メンタリングをする役割を置かないとうまくいかないだろう、ということはきっと想像できるのではないでしょうか。
また、その効果としてどんなものがあるかは、自分だけでは気づけ無い学びがありそうです。
ですが、その役割がトラステッドコミッターという名前なのかは、この章だけではわからないのでは？と思えました。
これは Getting Started with InnerSoruce のときにもお話しましたね。
