### ISSUE TITLE
Understanding~ Integration Review: 4-Passive Documentation~

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#82]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/4-passive-documentation-and-the-need-for-findability.md?plain=1

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/4-passive-documentation-and-the-need-for-findability.md?plain=1#L50

もっと皮肉を込めてもいいかも...
https://github.com/InnerSourceCommons/jp-contents/pull/72#discussion_r1066886619
"素晴らしいドキュメントはもうお読みになって??"

とかですかね。改めて読んだらちょっと皮肉がない表現になっていることに気づきました

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/4-passive-documentation-and-the-need-for-findability.md?plain=1#L58

ドキュメント→ドキュメンテーション

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/4-passive-documentation-and-the-need-for-findability.md?plain=1#L70

検索可能性
だけでもいいですかね

参考議論
https://github.com/InnerSourceCommons/jp-contents/pull/72#discussion_r1066722711

**Comment by yuhattor** [comment]
fyi: パッシブドキュメンテーションをどう訳すかに関する考察は以下にあります
https://github.com/InnerSourceCommons/jp-contents/pull/72#discussion_r1066696639

**Comment by masskaneko** [comment]
この章は難しいですね。また時間をとって読みます。
少なくとも document と documentation は明確に区別すべきでしょう。
documentation をドキュメントと訳している箇所がないかは要注意。
