### ISSUE TITLE
Understanding~ Integration Review: 5-Creating Good House Rules~

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#83]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/5-creating-good-house-rules-for-guests-writing-contributing-agreements.md?plain=1

**Comment by yuhattor** [comment]
問題ないと思います。とっても読みやすかったです。

https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/5-creating-good-house-rules-for-guests-writing-contributing-agreements.md?plain=1#L100

内容ではないですが、注釈の書き方は最後に統一だと思うので、そこだけ.. https://github.com/InnerSourceCommons/jp-contents/issues/68
