### ISSUE TITLE
Understanding~ Integration Review: 8-Looking Forward~

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#86]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/8-looking-forward.md?plain=1

**Comment by yuhattor** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/8-looking-forward.md?plain=1#L60

リンク切れです
