### ISSUE TITLE
Understanding~ Integration Review: 9-Actual Checklist

### ISSUE THREAD

**Issue by masskaneko** [yuhattor/japanese-contents#87]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/9-appendix.md?plain=1

**Comment by yuhattor** [comment]
日本語.md の形式のファイルを書くか、そのままにするかで言うと、英語のままで良い気がしています。
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/9-appendix.md?plain=1#L344


https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/9-appendix.md?plain=1#L322

**Comment by yuhattor** [comment]
カタカナ統一の方がよいかと
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/9-appendix.md?plain=1#L216

**Comment by yuhattor** [comment]
チェックリストですが

* こうするのでもいいですし

* [ ] せっかくマークダウンが使えるのでこちらでもいいかなと

どうでしょう(Gitbook とかに合わせると 箇条書きでもいいか...)

**Comment by yuhattor** [comment]
もとの文章がそうなので、仕方ないんですが
ハテナマークがついているものと、そうでないものなどが、混ざっており、
さらにその混ざり方が文のインデントレベルの中でも混ざってたりするので、
なんか気持ち悪い感じがしていますが...

まあこれはそんなもんでしょうか...笑

**Comment by masskaneko** [comment]
原著からしてそうなんですが、全てを箇条書きにすると頭の要素 (準備、リポジトリ…) が何なのかを見失いやすく感じました。

箇条書きの頭の要素を見出しレベル2 `##` にしてはどうでしょうか。
タイトルが実質的に見出しレベル1, 2 に分かれているのも冗長なので、見出しレベル1 にまとめればいいと思います。以下のように。

```
# 実際のチェックリスト

## 準備のチェックリスト

* 個人
* プロジェクト
・・・

## リポジトリのチェックリスト
```

**Comment by masskaneko** [comment]
https://github.com/InnerSourceCommons/jp-contents/blob/cbae441a014c84b3e9ff8a56765726288f2a3353/books/Understanding-the-InnerSource-Checklist/9-appendix.md?plain=1#L8

GNUマニュフェストとチェックリストマニュフェストが以下のものを指しているという訳注をつけたい

- https://www.gnu.org/gnu/manifesto.ja.html
- https://www.shinyusha.co.jp/media/checklist/ (The Checklist Manifesto の和訳書 "アナタはなぜチェックリストを使わないのか？"

**Comment by masskaneko** [comment]
The Apache Way も同様に訳注をつけたいところです。
https://www.apache.org/theapacheway/

**Comment by masskaneko** [comment]
これは感想です：
テキストの比率として準備(Readiness)が半分以上を占めています。準備はインナーソースを始めるための前提条件とも捉えられます。だとすると、日本でソフトウェアを作っている企業のうち、前提条件を満たしている企業が何割あるのか、1割あるだろうかと思えてきました。

もちろん PayPal もこの準備に書かれていることの多くを最初から満たしていたわけではないことは、本書からも、インナーソース入門(Getting Started with InnerSource)からもわかります。が、どれからの準備が必要かが読者層の企業とPayPalでどれほど違うのかは、今後のコミュニティ活動で抑えておきたいと思えました。
